### PR TITLE
Kafka streams binder issues in custom environment

### LINKED ISSUE #411: KStreamBinderConfiguration cannot find KafkaProperties when using multi-binder configuration
**Environment**
- JDK - 1.8.0_172
- Gradle - 4.8.1
- Spring Boot - 2.0.3.RELEASE
- Spring Cloud Stream - Elmhurst.SR1

**Description**

I ran into an issue similar to spring-cloud/spring-cloud-stream-binder-kafka#326 using Spring Boot with the Kafka streams binder when attempting to bridge a stream from an external Kafka cluster. When running my application, I get the following error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field kafkaProperties in org.springframework.cloud.stream.binder.kafka.streams.KStreamBinderConfiguration required a bean of type 'org.springframework.boot.autoconfigure.kafka.KafkaProperties' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.boot.autoconfigure.kafka.KafkaProperties' in your configuration.
```

**Code**

`build.gradle`
```gradle
buildscript {
	repositories {
        mavenCentral()
        jcenter()
        maven { url 'https://repo.spring.io/plugins-release' }
        maven { url 'https://plugins.gradle.org/m2' }
        mavenLocal()
	}
	dependencies {
		classpath 'org.springframework.boot:spring-boot-gradle-plugin:2.0.3.RELEASE'
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.esm.stream'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
	jcenter()
}

ext {
	springCloudVersion = 'Elmhurst.SR1'
}

dependencies {
    // Spring : Test
    testCompile 'org.springframework.boot:spring-boot-starter-test'
    testCompile 'org.springframework.cloud:spring-cloud-stream-test-support'
    
    // Spring : SCS
    compile 'org.springframework.cloud:spring-cloud-stream-binder-kafka-streams'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-stream-dependencies:${springCloudVersion}"
	}
}
```

`application.yml`
```yaml
spring.cloud.stream:
  bindings:
    input:
      binder: kBind1
  binders:
    kBind1:
      type: kstream
      environment:
        spring.cloud.stream.kafka.streams.binder:
          brokers: localhost:9093
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
```

`StreamSourceApplication.java`
```java
package com.esm.stream;

import java.util.Map;

import org.apache.kafka.streams.kstream.KStream;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.stream.annotation.EnableBinding;
import org.springframework.cloud.stream.annotation.Input;
import org.springframework.cloud.stream.annotation.StreamListener;

@SpringBootApplication()
@EnableBinding(com.esm.stream.StreamSourceApplication.StreamSourceProcessor.class)
public class StreamSourceApplication {
    
    public static void main(String[] args) {
        SpringApplication.run(StreamSourceApplication.class, args);
    }
    
    @StreamListener
    public void handle(@Input("input") KStream<Object, Map<String, Object>> stream) {
       stream.foreach((k, v) -> {
           System.out.println("\n" + k + ":\n" + v + "\n");
       });
    }
    
    interface StreamSourceProcessor {
        @Input("input")
        KStream<?, ?> inputStream();
    }
}
```

### PR DESCRIPTION
**Pull request by sobychacko**
When kafka streams binder is used in the context of a custom environment, possibly
for a multi binder use case, it is unable to query the outer context as the normal
parent context is absent. This change will ensure that the binder context has access
to the outer context so that it can use any beans it needs from it in KStream or KTable
binder configuration.

Resolves #411

### CODE REVIEW

File: spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KStreamBinderConfiguration.java [hunk 1]
```diff
@@ -16,36 +16,49 @@
...
+			ApplicationContext outerContext = (ApplicationContext) beanFactory.getBean("outerContext");
+			beanFactory.registerSingleton("kafkaStreamsBinderConfigurationProperties", outerContext
+					.getBean(KafkaStreamsBinderConfigurationProperties.class));
+			beanFactory.registerSingleton("kafkaStreamsMessageConversionDelegate", outerContext
+					.getBean(KafkaStreamsMessageConversionDelegate.class));
+			beanFactory.registerSingleton("kafkaStreamsBindingInformationCatalogue", outerContext
+					.getBean(KafkaStreamsBindingInformationCatalogue.class));
+			beanFactory.registerSingleton("keyValueSerdeResolver", outerContext
+					.getBean(KeyValueSerdeResolver.class));
+			beanFactory.registerSingleton("kafkaStreamsExtendedBindingProperties", outerContext
```
Comment (olegz) [inline spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KStreamBinderConfiguration.java]: Soby, should it be something like
```
beanFactory.registerSingleton(KeyValueSerdeResolver.class.getSimpleName(), outerContext.getBean(KeyValueSerdeResolver.class));
```
We really don't care about the name to begin with, so why not just delegate it to class name?

Comment (sobychacko) [reply spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KStreamBinderConfiguration.java]: Done. Changed all those calls with that.

**Comment by sobychacko** [comment]
Merged this PR upstream.
