### PR TITLE
Kafka binder JAAS config refactoring

### LINKED ISSUE #459: Incorrect property validation in JassLoginModuleConfiguration
```
	public void setControlFlag(String controlFlag) {
		Assert.notNull(controlFlag, "cannot be null");
		if (AppConfigurationEntry.LoginModuleControlFlag.OPTIONAL.equals(controlFlag)) {
			this.controlFlag = AppConfigurationEntry.LoginModuleControlFlag.OPTIONAL;
		}
		else if (AppConfigurationEntry.LoginModuleControlFlag.REQUIRED.equals(controlFlag)) {
			this.controlFlag = AppConfigurationEntry.LoginModuleControlFlag.REQUIRED;
		}
		else if (AppConfigurationEntry.LoginModuleControlFlag.REQUISITE.equals(controlFlag)) {
			this.controlFlag = AppConfigurationEntry.LoginModuleControlFlag.REQUISITE;
		}
		else if (AppConfigurationEntry.LoginModuleControlFlag.SUFFICIENT.equals(controlFlag)) {
			this.controlFlag = AppConfigurationEntry.LoginModuleControlFlag.SUFFICIENT;
		}
		else {
			throw new IllegalArgumentException(controlFlag + " is not a supported control flag");
		}
	}
```

Comparing `LoginModuleControlFlag.equals(String)` will never return `true`.

### PR DESCRIPTION
**Pull request by sobychacko**
Refactor JaasLoginModuleConfiguraton to leverage ControlFlag enum from
spring-kafka, instead of directly using LoginModuleControlFlag from JDK.

Re-instate Jass configuration tests.

Resolves #459

### CODE REVIEW

File: spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderJaasInitializerListenerTest.java [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+				.isInstanceOf(ConfigurationPropertiesBindException.class)
+				.hasMessageContaining("Error creating bean with name 'configurationProperties'");
+	}
+
+
+	@SpringBootApplication
+	public static class SimpleApplication {
+
+	}
+}
```
Comment (garyrussell) [inline spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderJaasInitializerListenerTest.java]: Needs linefeed.

File: spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderJaasInitializerListenerTest.java [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+import static org.assertj.core.api.Assertions.assertThatThrownBy;
+
+/**
+ * @author Marius Bogoevici
+ * @author Soby Chacko
+ */
+public class KafkaBinderJaasInitializerListenerTest {
+
+	@Test
+	public void testConfigurationParsedCorrectlyWithKafkaClientAndDefaultControlFlag() throws Exception {
```
Comment (garyrussell) [inline spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderJaasInitializerListenerTest.java]: This test is hanging for me...

```
"main" #1 prio=5 os_prio=31 tid=0x00007fdf34006000 nid=0x1803 in Object.wait() [0x000070000e35b000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1252)
	- locked <0x000000076bfd7f40> (a org.apache.kafka.common.utils.KafkaThread)
	at java.lang.Thread.join(Thread.java:1326)
	at org.apache.kafka.clients.admin.KafkaAdminClient.close(KafkaAdminClient.java:461)
	at org.apache.kafka.clients.admin.AdminClient.close(AdminClient.java:72)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.doProvisionConsumerDestination(KafkaTopicProvisioner.java:206)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionConsumerDestination(KafkaTopicProvisioner.java:155)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionConsumerDestination(KafkaTopicProvisioner.java:74)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:344)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:90)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:131)
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:167)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:148)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:234)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:54)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle$$Lambda$515/680227777.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:47)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:33)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	- locked <0x00000007915d5de0> (a java.lang.Object)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1256)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1244)
	at org.springframework.cloud.stream.binder.kafka.KafkaBinderJaasInitializerListenerTest.testConfigurationParsedCorrectlyWithKafkaClientAndDefaultControlFlag(KafkaBinderJaasInitializerListenerTest.java:45)
```

There are other hung threads too

```
"task-scheduler-3" #166 prio=5 os_prio=31 tid=0x00007fdf37ad1000 nid=0x960f in Object.wait() [0x000070000fcd2000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:110)
	- locked <0x000000076d2e2da8> (a org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:274)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createTopicAndPartitions(KafkaTopicProvisioner.java:311)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createTopicIfNecessary(KafkaTopicProvisioner.java:291)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createTopic(KafkaTopicProvisioner.java:275)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.doProvisionConsumerDestination(KafkaTopicProvisioner.java:188)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionConsumerDestination(KafkaTopicProvisioner.java:155)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionConsumerDestination(KafkaTopicProvisioner.java:74)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:344)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:90)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:131)
	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleConsumerBinding$0(BindingService.java:187)
	at org.springframework.cloud.stream.binding.BindingService$$Lambda$538/1273093350.run(Unknown Source)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
```

```
"task-scheduler-1" #161 prio=5 os_prio=31 tid=0x00007fdf34027800 nid=0xa21f in Object.wait() [0x000070000f8c7000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1252)
	- locked <0x000000076d611730> (a org.apache.kafka.common.utils.KafkaThread)
	at java.lang.Thread.join(Thread.java:1326)
	at org.apache.kafka.clients.admin.KafkaAdminClient.close(KafkaAdminClient.java:461)
	at org.apache.kafka.clients.admin.AdminClient.close(AdminClient.java:72)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:148)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:74)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:171)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:90)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:138)
	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleProducerBinding$2(BindingService.java:340)
	at org.springframework.cloud.stream.binding.BindingService$$Lambda$537/943613748.run(Unknown Source)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
```

File: spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderJaasInitializerListenerTest.java [hunk 3]
```diff
@@ -36,6 +40,24 @@
  */
 public class KafkaBinderJaasInitializerListenerTest {
 
+	private static final String KAFKA_BROKERS_PROPERTY = "spring.cloud.stream.kafka.binder.brokers";
+	private static final String ZK_NODE_PROPERTY = "spring.cloud.stream.kafka.binder.zkNodes";
```
Comment (garyrussell) [inline spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderJaasInitializerListenerTest.java]: We no longer need zknodes (since 2.0).

Comment (sobychacko) [reply spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderJaasInitializerListenerTest.java]: copy/paste, will address soon.
